/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nvz.mrpc;

import org.junit.Test;
import static org.junit.Assert.*;

public class RpcUtilsTest {
    @Test public void defaultControllerExists() {
        assertNotNull("RpcUtils has default controller", RpcUtils.getDefaultController());
    }
}
